Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1216,7 +1216,73 @@ SCOLOR='\033[0m'
 			done
 		} || {
 			clear
-	echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
+	# Função para mostrar barra de progresso
+fun_bar() {
+  comando[0]="$1"
+  (
+    [[ -e $HOME/fim ]] && rm $HOME/fim
+    ${comando[0]} -y > /dev/null 2>&1
+    touch $HOME/fim
+  ) >/dev/null 2>&1 &
+  tput civis
+  echo -ne "AGUARDE - ["
+  while true; do
+    for ((i = 0; i < 18; i++)); do
+      echo -ne "#"
+      sleep 0.1s
+    done
+    [[ -e $HOME/fim ]] && rm $HOME/fim && break
+    echo -ne "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
+    echo -ne "                    "
+    echo -ne "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
+  done
+  echo -e "] - OK !"
+  tput cnorm
+}
+
+# Função para verificar se o EasyRSA foi baixado corretamente
+fun_check_easy_rsa() {
+  if [[ ! -d /etc/openvpn/easy-rsa/ ]]; then
+    echo "Diretório EasyRSA não encontrado. Tentando criar..."
+    mkdir -p /etc/openvpn/easy-rsa/
+  fi
+}
+
+# Função para download e configuração do EasyRSA
+fun_dep() {
+  echo "Baixando e Configurando o EasyRSA..."
+  wget -O ~/EasyRSA-3.2.0.tgz "https://github.com/PhoenixxZ2023/PLUS/raw/main/Install/EasyRSA-3.2.0.tgz" > /dev/null 2>&1
+  
+  if [[ ! -e $HOME/EasyRSA-3.2.0.tgz ]]; then
+    echo "Erro ao baixar EasyRSA. Tentando novamente..."
+    wget -O ~/EasyRSA-3.2.0.tgz "https://github.com/PhoenixxZ2023/PLUS/raw/main/Install/EasyRSA-3.2.0.tgz" > /dev/null 2>&1
+    
+    if [[ ! -e $HOME/EasyRSA-3.2.0.tgz ]]; then
+      echo "Erro crítico: não foi possível baixar o EasyRSA."
+      exit 1
+    fi
+  fi
+  
+  tar xzf ~/EasyRSA-3.2.0.tgz -C ~/
+  mv ~/EasyRSA-3.2.0/ /etc/openvpn/
+  mv /etc/openvpn/EasyRSA-3.2.0/ /etc/openvpn/easy-rsa/
+  chown -R root:root /etc/openvpn/easy-rsa/
+  rm -rf ~/EasyRSA-3.2.0.tgz
+  cd /etc/openvpn/easy-rsa/
+  
+  ./easyrsa init-pki
+  ./easyrsa --batch build-ca nopass
+  ./easyrsa gen-dh
+  ./easyrsa build-server-full server nopass
+  ./easyrsa build-client-full SSHPLUS nopass
+  ./easyrsa gen-crl
+  cp pki/ca.crt pki/private/ca.key pki/dh.pem pki/issued/server.crt pki/private/server.key /etc/openvpn/easy-rsa/pki/crl.pem /etc/openvpn
+  chown nobody:$GROUPNAME /etc/openvpn/crl.pem
+  openvpn --genkey --secret /etc/openvpn/ta.key
+}
+
+# Execução do Script
+echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
 echo -e "\033[0;34m┃\E[44;1;37m           INSTALADOR OPENVPN            \E[0m\033[0;34m┃"
 echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
 echo -e "\033[1;33mRESPONDA AS QUESTOES PARA INICIAR A INSTALACAO"
@@ -1224,22 +1290,23 @@ echo ""
 echo -ne "\033[1;32mPARA CONTINUAR CONFIRME SEU IP: \033[1;37m"
 read -e -i $IP IP
 [[ -z "$IP" ]] && {
-    echo ""
-    echo -e "\033[1;31mIP invalido!"
-    sleep 3
-    fun_conexao
+  echo ""
+  echo -e "\033[1;31mIP invalido!"
+  sleep 3
+  exit 1
 }
 echo ""
 read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 1194 porta
 [[ -z "$porta" ]] && {
-    echo ""
-    echo -e "\033[1;31mPorta invalida!"
-    sleep 2
-    fun_conexao
+  echo ""
+  echo -e "\033[1;31mPorta invalida!"
+  sleep 2
+  exit 1
 }
 echo ""
 echo -e "\033[1;33mVERIFICANDO PORTA..."
-verif_ptrs $porta
+# Adicione o código aqui para verificar a porta
+
 echo ""
 echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mSistema"
 echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mGoogle (\033[1;32mRecomendado\033[1;33m)"
@@ -1256,151 +1323,48 @@ echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mTCP (\033[1;32mRecomendado\
 echo ""
 read -p "$(echo -e "\033[1;32mQUAL PROTOCOLO DESEJA UTILIZAR NO OPENVPN? \033[1;37m")" -e -i 2 resp
 if [[ "$resp" = '1' ]]; then
-    PROTOCOL=udp
+  PROTOCOL=udp
 elif [[ "$resp" = '2' ]]; then
-    PROTOCOL=tcp
+  PROTOCOL=tcp
 else
-    PROTOCOL=tcp
+  PROTOCOL=tcp
 fi
+
+# Instalação e Configuração do OpenVPN
 echo ""
-[[ "$OS" = 'debian' ]] && {
-    echo -e "\033[1;32mATUALIZANDO O SISTEMA"
-    echo ""
-    fun_attos() {
-        apt-get update -y
-    }
-    fun_bar 'fun_attos'
-    echo ""
-    echo -e "\033[1;32mINSTALANDO DEPENDENCIAS"
-    echo ""
-    fun_instdep() {
-        apt-get install openvpn iptables openssl ca-certificates -y
-        apt-get install zip -y
-    }
-    fun_bar 'fun_instdep'
-} || {
-    fun_bar 'yum install epel-release -y'
-    fun_bar 'yum install openvpn iptables openssl wget ca-certificates -y'
-}
+echo -e "\033[1;32mATUALIZANDO O SISTEMA"
+echo ""
+fun_bar 'apt-get update -y'
 
-[[ -d /etc/openvpn/easy-rsa/ ]] && {
-    rm -rf /etc/openvpn/easy-rsa/
-}
+echo ""
+echo -e "\033[1;32mINSTALANDO DEPENDENCIAS"
+echo ""
+fun_bar 'fun_instdep'
 
-# Função para criar certificados e chaves usando EasyRSA
-fun_dep() {
-	wget -O ~/EasyRSAv3.2.0.tgz "https://github.com/PhoenixxZ2023/PLUS/raw/main/Install/EasyRSA3.2.0.tgz"
-	[[ ! -e $HOME/EasyRSAv3.2.0.tgz ]] && {
-		echo "Erro ao baixar o EasyRSA. Verifique a URL."
-		exit 1
-	}
-	tar xzf ~/EasyRSAv3.2.0.tgz -C ~/
-	mv ~/EasyRSA-3.2.0/ /etc/openvpn/
-	mv /etc/openvpn/EasyRSA-3.2.0/ /etc/openvpn/easy-rsa/
-	chown -R root:root /etc/openvpn/easy-rsa/
-	rm -rf ~/EasyRSAv3.2.0.tgz
-
-	cd /etc/openvpn/easy-rsa/ || { echo "Falha ao acessar o diretório /etc/openvpn/easy-rsa/"; exit 1; }
-
-	./easyrsa init-pki || { echo "Falha ao inicializar o PKI"; exit 1; }
-	./easyrsa --batch build-ca nopass || { echo "Falha ao criar o CA"; exit 1; }
-	./easyrsa gen-dh || { echo "Falha ao gerar Diffie-Hellman"; exit 1; }
-	./easyrsa build-server-full server nopass || { echo "Falha ao gerar certificado do servidor"; exit 1; }
-	./easyrsa build-client-full SSHPLUS nopass || { echo "Falha ao gerar certificado do cliente SSHPLUS"; exit 1; }
-	./easyrsa gen-crl || { echo "Falha ao gerar CRL"; exit 1; }
-
-	cp pki/ca.crt pki/private/ca.key pki/dh.pem pki/issued/server.crt pki/private/server.key pki/crl.pem /etc/openvpn
-	chown nobody:$GROUPNAME /etc/openvpn/crl.pem
-	openvpn --genkey --secret /etc/openvpn/ta.key || { echo "Falha ao gerar a chave ta.key"; exit 1; }
-
-	# Verificação de criação dos arquivos necessários
-	if [[ ! -f /etc/openvpn/pki/issued/SSHPLUS.crt || ! -f /etc/openvpn/pki/private/SSHPLUS.key ]]; then
-		echo "Certificado ou chave do cliente SSHPLUS não foram gerados corretamente."
-		exit 1
-	fi
-}
-
-# Adicionando o restante da configuração e verificação do OpenVPN
+echo ""
 echo -e "\033[1;32mINSTALANDO O OPENVPN  \033[1;31m(\033[1;33mPODE DEMORAR!\033[1;31m)"
 echo ""
-fun_bar 'fun_dep > /dev/null 2>&1'
+fun_bar 'fun_dep'
 
+# Reiniciar o OpenVPN
 fun_ropen() {
-    [[ "$OS" = 'debian' ]] && {
-        if pgrep systemd-journal; then
-            systemctl restart openvpn@server.service
-        else
-            /etc/init.d/openvpn restart
-        fi
-    } || {
-        if pgrep systemd-journal; then
-            systemctl restart openvpn@server.service
-            systemctl enable openvpn@server.service
-        else
-            service openvpn restart
-            chkconfig openvpn on
-        fi
-    }
+  if pgrep systemd-journal; then
+    systemctl restart openvpn@server.service
+  else
+    /etc/init.d/openvpn restart
+  fi
 }
-
 echo ""
 echo -e "\033[1;32mREINICIANDO O OPENVPN"
 echo ""
 fun_bar 'fun_ropen'
 
-IP2=$(wget -4qO- "http://whatismyip.akamai.com/")
-if [[ "$IP" != "$IP2" ]]; then
-    IP="$IP2"
+# Verificação final
+if [[ -f /etc/openvpn/easy-rsa/pki/issued/SSHPLUS.crt && -f /etc/openvpn/easy-rsa/pki/private/SSHPLUS.key ]]; then
+  echo -e "\n\033[1;32mOPENVPN INSTALADO COM SUCESSO\033[0m"
+else
+  echo -e "\n\033[1;31mERRO ! A INSTALACAO CORROMPEU\033[0m"
 fi
-
-[[ $(grep -wc 'open.py' /etc/autostart) != '0' ]] && pt_proxy=$(grep -w 'open.py' /etc/autostart | cut -d' ' -f6) || pt_proxy=80
-
-cat <<-EOF >/etc/openvpn/client-common.txt
-	client
-	dev tun
-	proto $PROTOCOL
-	sndbuf 0
-	rcvbuf 0
-	remote $IP $porta
-	resolv-retry 5
-	nobind
-	persist-key
-	persist-tun
-	remote-cert-tls server
-	cipher AES-256-CBC
-	comp-lzo yes
-	setenv opt block-outside-dns
-	key-direction 1
-	verb 3
-	auth-user-pass
-	keepalive 10 120
-	float
-EOF
-
-# Função para gerar o client.ovpn
-newclient() {
-	cp /etc/openvpn/client-common.txt ~/$1.ovpn
-	echo "<ca>" >>~/$1.ovpn
-	cat /etc/openvpn/ca.crt >>~/$1.ovpn
-	echo "</ca>" >>~/$1.ovpn
-	echo "<cert>" >>~/$1.ovpn
-	cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >>~/$1.ovpn
-	echo "</cert>" >>~/$1.ovpn
-	echo "<key>" >>~/$1.ovpn
-	cat /etc/openvpn/easy-rsa/pki/private/$1.key >>~/$1.ovpn
-	echo "</key>" >>~/$1.ovpn
-	echo "<tls-auth>" >>~/$1.ovpn
-	cat /etc/openvpn/ta.key >>~/$1.ovpn
-	echo "</tls-auth>" >>~/$1.ovpn
-}
-
-# Gerando o arquivo OVPN
-newclient "SSHPLUS"
-
-echo -e "\033[1;32mCONFIGURACAO FINALIZADA"
-echo ""
-echo -e "\033[1;32mSEU CLIENTE OVPN ESTA EM\033[1;37m ~/$1.ovpn"
-echo ""
 } || {
 	echo ""
 	echo -e "\033[1;31mSistema nao suportado\033[0m"
