Update menu

diff --git a/Modulos/menu b/Modulos/menu
--- a/Modulos/menu
+++ b/Modulos/menu
@@ -343,60 +343,56 @@ case "$x" in
    sleep 2
 esac
 }
-while true $x != "ok"
-do
-stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
-stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
-stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
-stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
-if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
-system=$(cut -d' ' -f1 /etc/issue.net)
-system+=$(echo ' ')
-system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
-elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
-system=$(cut -d' ' -f1 /etc/issue.net)
-system+=$(echo ' ')
-system+=$(cut -d' ' -f3 /etc/issue.net)
-else
-system=$(cut -d' ' -f1 /etc/issue.net)
-fi
-_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
-[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
-[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
-[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
-_onli=$(($_ons + $_onop + $_ondrp))
-_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
-_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
-_usop=$(printf '%-5s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
-_core=$(printf '%-5s' "$(grep -c cpu[0-9] /proc/stat)")
-_system=$(printf '%-10s' "$system")
-_hora=$(printf '%(%H:%M:%S)T')
-_onlin=$(printf '%-5s' "$_onli")
-_userexp=$(printf '%-5s' "$_expuser")
-_tuser=$(printf '%-5s' "$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)")
-[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m(ON ◉ ") || stsf=$(echo -e "\033[1;31m(OFF ○ ") 
-stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
-stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
-stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
-stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
-stsom=$(ps x | grep "shutdown -r 16:00"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○) ")
-autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○)")
-swap1=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $2'})")
-swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
-swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
-clear
-echo -e "\033[1;37mSEU IP 👉 \033[38;5;82m$IP           \033[1;36mTELEGRAM 😎\033 \033[1;37m @TURBONET2023"
-echo -e "\033[0;34m╔══════════════════════════════════════════════════════════╗\033[0m"
-echo -e "\033[0;34m║\E[46;1;37m                   TURBONET_SSH_SCRIPT_PRO                \E[0m\033[0;34m║"
-echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
-echo -e "\033[0;34m║\033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM       \033[1;31m \033[1;32mPROCESSADOR        \033[0;34m║"
-echo -e "\033[0;34m║\033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram  \033[1;31m \033[1;36mNucleos: \033[1;37m$_core\033[0m     \033[0;34m║"
-echo -e "\033[0;34m║\033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usor  \033[1;31m \033[1;36mEm uso: \033[1;37m$_usop\033[0m      \033[0;34m║"  
-echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
-echo -e "\033[0;34m║\033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser       \033[0;34m║"
-echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
-echo -e "\033[0;34m║\033[1;32mBADVPN-PRO/UDP \033[1;37m$stsu      \033[1;31m              \033[1;31m  \033[1;32mLIMITADOR-SSH \033[1;37m$stsl   \033[0;34m║"
-echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
+# Infinite loop to keep the script running
+while true; do
+    # Checking process statuses and setting status variables
+    if command -v ps &> /dev/null; then
+        stsl=$(ps x | grep "limiter" | grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉)" || echo -e "\033[1;31m(OFF)")
+        stson=$(ps x | grep "onlineapp" | grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉)" || echo -e "\033[1;31m(OFF)")
+        stsu=$(ps x | grep "udpvpn" | grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉)" || echo -e "\033[1;31m(OFF)")
+        stsbot=$(ps x | grep "bot_plus" | grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉)" || echo -e "\033[1;31m(OFF)")
+    else
+        echo "ps command not found."
+        exit 1
+    fi
+
+    # Identifying the operating system
+    if grep -q "Ubuntu" /etc/issue.net; then
+        system="Ubuntu $(awk -F '.' '{print $1}' /etc/issue.net)"
+    elif grep -q "Debian" /etc/issue.net; then
+        system="Debian $(awk '{print $3}' /etc/issue.net)"
+    else
+        system=$(awk '{print $1}' /etc/issue.net)
+    fi
+
+    # Getting user and connection information
+    _ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
+    _expuser=$(cat /etc/SSHPlus/Exp 2>/dev/null || echo "0")
+    _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log 2>/dev/null || echo "0")
+    _ondrp=$(($(ps aux | grep dropbear | grep -v grep | wc -l) - 1))
+    _onli=$(($_ons + $_onop + $_ondrp))
+    _ram=$(free -h | awk '/^Mem:/ {print $2}')
+    _usor=$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')
+    _usop=$(top -bn1 | awk '/Cpu/ { cpu = 100 - $8 "%"}; END { print cpu }')
+    _core=$(grep -c cpu[0-9] /proc/stat)
+    _hora=$(date '+%H:%M:%S')
+    _tuser=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
+    stsf=$(test -e /etc/Plus-torrent && echo -e "\033[1;32m(ON◉)" || echo -e "\033[1;31m(OFF)")
+
+    # Clear the screen and display system information
+    clear
+    echo -e "\033[1;37mSEU IP 👉 \033[38;5;82m$IP           \033[1;36mTELEGRAM 😎\033 \033[1;37m @TURBONET2023"
+    echo -e "\033[0;34m╔══════════════════════════════════════════════════════════╗\033[0m"
+    echo -e "\033[0;34m║\E[46;1;37m                   TURBONET_SSH_SCRIPT_PRO                \E[0m\033[0;34m║"
+    echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
+    echo -e "\033[0;34m║\033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM       \033[1;31m \033[1;32mPROCESSADOR        \033[0;34m║"
+    echo -e "\033[0;34m║\033[1;36mOS: \033[1;37m$system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram  \033[1;31m \033[1;36mNúcleos: \033[1;37m$_core\033[0m     \033[0;34m║"
+    echo -e "\033[0;34m║\033[1;36mHora: \033[1;37m$_hora    \033[1;31m  \033[1;36mEm uso: \033[1;37m$_usor  \033[1;31m \033[1;36mEm uso: \033[1;37m$_usop\033[0m      \033[0;34m║"  
+    echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
+    echo -e "\033[0;34m║\033[1;32mOnlines:\033[1;37m $_onli    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_expuser \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser       \033[0;34m║"
+    echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
+    echo -e "\033[0;34m║\033[1;32mBADVPN-PRO/UDP \033[1;37m$stsu      \033[1;31m              \033[1;31m  \033[1;32mLIMITADOR-SSH \033[1;37m$stsl   \033[0;34m║"
+    echo -e "\033[0;34m╠══════════════════════════════════════════════════════════╣\033[0m"
 echo -e "\033[0;34m║\033[0;31m[\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mCRIAR USUARIO \033[0;31m          [\033[1;36m15\033[0;31m] \033[1;37m• \033[1;37mSPEEDTEST  \033[0;34m         ║"       
 echo -e "\033[0;34m║\033[0;31m[\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mCRIAR TESTE         \033[0;31m    [\033[1;36m16\033[0;31m] \033[1;37m• \033[1;37mBANNER  \033[0;34m            ║"         
 echo -e "\033[0;34m║\033[0;31m[\033[1;36m03\033[0;31m] \033[1;37m\033[1;37m• \033[1;37mREMOVER USUARIO \033[0;31m        [\033[1;36m17\033[0;31m] \033[1;37m• \033[1;37mTRAFEGO \033[0;34m            ║" 
